### ISSUE TITLE
Checklist before next release.

### ISSUE THREAD

**Issue by myronmarston** [seomoz/qless#132]
The unified branch just got merge and the 0.10 release is near.  There are some things I want to fix, first, though:
- [ ] Rename `backlog` recurring job option to `max_backlog`. This makes its purpose and use more clear.  It should be changed in qless-core, too.
- [ ] Deprecate `queue_history` and `raw_queue_history`, opting instead for `history` and `raw_history`. The "queue" names made sense back in the day when the history had one item per queue.  Now it doesn't.  The non-raw history should return `Qless::Queue` objects in place of queue names.
- [ ] Fix `Qless::Queue#length` to call the `length` lua function rather than doing multiple redis calls.
- [x] Fix `Qless::Middleware::RetryExceptions` so that it passes the proper group and failure to `Job#retry` so that the failure group gets logged in the history.
- [x] Fix `Qless::Middleware::Metriks` to use a period as the separator character rather than a colon.  This is in line with what the Metriks gem and librato-metrics gems use.
- [ ] Update README to document new features.
- [ ] Consider adding a change log?
